### ISSUE TITLE
[Bug]: Mystical agriculture - infusion stones

### ISSUE THREAD

**Issue by CarterDrops** [ModernGamingWorld/Monumental-Experience#12]
### General Info

- [ ] I didn't added any mods
- [ ] I get this issue consistently in single-player
- [X] I get this issue consistently in multi-player
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

curseforge

### Modpack version

2.2.193

### Describe your issue

the infusion crystals break after the second use no matter which version they are when used in the mixer which is the only way to progress  

### Steps to reproduce the issue

try make hight tier essence in the mixer with any crystal 

### Additional Information

n/a

**Comment by ModernGamingWorld** [comment]
Not an issue, as some one else reported the samething and I deleted it

![Screenshot_2024-08-16_093234](https://github.com/user-attachments/assets/862c1c66-4581-4e07-ade4-076cb7caf003)
