### ISSUE TITLE
[Bug]: Logging level is too low

### ISSUE THREAD

**Issue by Mexolius** [ModernGamingWorld/Monumental-Experience#13]
### General Info

- [X] I didn't added any mods
- [X] I get this issue consistently in single-player
- [X] I get this issue consistently in multi-player
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

2.0.65

### Describe your issue

The logging level is set to TRACE and the latest.log file gets really big really fast. Talking 5GBs in 2 hours of server runtime. This is enough to make most hostings very, very unhappy.

### Steps to reproduce the issue

Start the server with basic configurations
Go to logs/latest.log
Check the size and contents of the file

### Additional Information

Minecraft version 1.20.1
Forge 47.3.11
Suggestion: Set logging level to INFO and reduce logging in general (there maybe other setting like glDebugVerbosity that need to be tweaked [googled])

Sorry for no logs but uploading a 5GB file is not doable

**Comment by ModernGamingWorld** [comment]
I mean how is this an issue, whenever I have not touched anything related to the logs
