### ISSUE TITLE
[Suggestion]: pylons

### ISSUE THREAD

**Issue by Tesik1992** [ModernGamingWorld/Monumental-Experience#18]
### General Info

- [X] I would like to suggest a new mod
- [ ] I would like to suggest a new quests
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Its posible to add pylons on monumentals experience with strongest craft reception ?:)

**Comment by ModernGamingWorld** [comment]
I'll look into this after the Holidays next week
