### ISSUE TITLE
[Bug]: PneumaticCraft Luminessence recipe is not working

### ISSUE THREAD

**Issue by readytodream** [ModernGamingWorld/Monumental-Experience#4]
### General Info

- [ ] I didn't added any mods
- [X] I get this issue consistently in single-player
- [X] I get this issue consistently in multi-player
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

V2.2.140 (Release)

### Describe your issue

Trying to craft Luminessence in the Pressure Chamber but the max pressure is 5 and the recipe requires 7.

### Steps to reproduce the issue

Make Pressure Chamber
Add ingredients
Nothing happens

### Additional Information

Trying to craft Luminessence in the Pressure Chamber but the max pressure is 5 and the recipe requires 7.

**Comment by ModernGamingWorld** [comment]
https://www.curseforge.com/minecraft/mc-mods/moderns-monumental-recipe/files/5336715

**Comment by readytodream** [comment]
I'm sorry I don't understand how this fixes the problem? I see it says it changes some recipes but I don't see any changes it makes to the pressure chamber

**Comment by ModernGamingWorld** [comment]
@readytodream that said link is the mod that handles your issue, I fixed it by lowering the pressure to 5. there is nothing else wrong with it

**Comment by ModernGamingWorld** [comment]
@readytodream Try the new version of my Mod that I am posting here tonight, just go in the mods folder and remove the old modernrecipes mod version and replace it with the new one out tonight and see if that fixes it

**Comment by readytodream** [comment]
I've done that and it now says it needs 5 pressure but doesn't craft, I think I will give up with this method and work on one of the other recipes. Thanks for the help.
