### ISSUE TITLE
[Bug]: Farmer's Delight items and blocks showing their internal names

### ISSUE THREAD

**Issue by Crundt** [ModernGamingWorld/Monumental-Experience#5]
### General Info

- [X] I didn't added any mods
- [X] I get this issue consistently in single-player
- [X] I get this issue consistently in multi-player
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

Curseforge

### Modpack version

2.2.148

### Describe your issue

Anything from Farmer's Delight shows their internal name rather than their formatted name.
So for example, stove is block.farmersdelight.stove instead of stove

### Steps to reproduce the issue

1: Make a creative world
2: Obtain a stove
3: Appears as block.farmersdelight.stove
(Applies to everything from farmer's delight)

### Additional Information

Screenshot: [https://imgur.com/a/S0D1crT](https://imgur.com/a/S0D1crT)
Log: https://gist.github.com/Crundt/11107c4946c5ee4accdc1339bbff42dc

**Comment by ModernGamingWorld** [comment]
As reported on Discord, this issue is a mod-related issue, and can't be fixed on my end unless the mod updates. Most developers moved on to 1.20.6, so it's very slim that it will be fixed

**Comment by Crundt** [comment]
I fixed it

**Comment by Crundt** [comment]
It just requires a resourcepack

**Comment by ModernGamingWorld** [comment]
okay

**Comment by ModernGamingWorld** [comment]
is said resourcepack something u did or something you can get off curseforge? @Crundt

**Comment by Crundt** [comment]
Something I did myself

**Comment by ModernGamingWorld** [comment]
okay

**Comment by Crundt** [comment]
I posted the resourcepack
[https://www.curseforge.com/minecraft/texture-packs/fd-issue-fix](https://www.curseforge.com/minecraft/texture-packs/fd-issue-fix)
