### ISSUE TITLE
[Bug]: Tinkers is entirely unaccessible due to Create, which requires you to get enough iron, zinc, and nether materials to make a simple forge

### ISSUE THREAD

**Issue by AccountNameIsTaken** [ModernGamingWorld/Monumental-Experience#9]
### General Info

- [X] I didn't added any mods
- [X] I get this issue consistently in single-player
- [X] I get this issue consistently in multi-player
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

ATLauncher

### Modpack version

1.19.2

### Describe your issue

Tinkers Construct is entirely unaccessible due to Create, which requires you to get enough iron, zinc, and nether materials to make a simple forge.

This would be attainable but the nether seems to be blocked due to something else, and all of the tinkers quests and books say you can make grout normally, and not without all the Create bogus. 
Please either remove Create or add a toggle.

Thanks!

### Steps to reproduce the issue

To get an iron pickaxe, one must first:

1. create all the tinkers benches
2. create an entire waterwheel-to-gear ratio device with 40+ iron
3. go to the nether and capture a blaze (impossible, nether portals don't work)
4. finally hook up all the machinery, feed the blaze so it doesn't go out
5. collect sand, gravel, and clay in massive amounts, using even more iron to flatten the clay to plates
6. finally get grout.
7. then build the entire tinkers' furnace and start smelting iron
8. make several casts and casting tables and finally make a pickaxe head

I know this mod is marked as hard but Create blocking progress everywhere is insane.

### Additional Information

N/A

**Comment by AccountNameIsTaken** [comment]
Recommended course of action: delete all create mods

**Comment by AccountNameIsTaken** [comment]
Recommended removing these jars

![image](https://github.com/user-attachments/assets/87cb76e1-250c-4084-9329-779b297a6a30)

**Comment by ModernGamingWorld** [comment]
@AccountNameIsTaken I will not be removing Create, as it is used in alot of custom recipes.

nether seems to be blocked due to something else, this is not true. Use the Nether painting

**Comment by ModernGamingWorld** [comment]
I will say this much, you are the only one having this problem. No one else has had a single issue with the modpack, I am not removing a ton of mods because you are having trouble.

You can also get all the tools, like Iron pickaxes, using the Smithing Table if you read the quest book. Smithing tables are found around the world as well

**Comment by AccountNameIsTaken** [comment]
Word I respect that, I just want to acknowledge that both the tinkers' construct book and the quest book say you can make grout the normal way; so maybe just take note of that. Maybe make mention of it in the quest book tutorials, or just grant the player 128 seared bricks to circumvent the grout route.

**Comment by ModernGamingWorld** [comment]
I'll have Dexx take a look whenever he can. hes fixed the other books in the pack
